fix: add mimetype guard
Previously the not found script file gives the error message:
SyntaxError: Unexpected token '<'

This because there's no guard for mimetype at that time. Now, it fixed.